### ISSUE TITLE
can support centos6 or 7？

### ISSUE THREAD

**Issue by yangzhixiao** [jtstorck/containerized-ambari#1]
RT

**Comment by jtstorck** [comment]
Eventually I might add Centos7 support, but not Centos6.  Currently, Centos7 docker images are problematic with systemctl usage in Docker, which is why this project is currently based on Ubuntu16.  However, there are some issues with the HDFS component installation, since it appears that hadoop-functions.sh is/was missing from the Ubuntu16 HDFS packages.  I have not yet gone back to check to see if this is been resolved in HDFS.
